package agentflow

import (
	"context"

	"github.com/PabloGalante/farum-agent/internal/domain"
)

// AgentInput represent whats every agent receives
type AgentInput struct {
	// Original User Message (for the first agent)
	UserMessage string

	// Current conversational context (history, mode, metadata)
	ConvCtx domain.ConversationContext
}

// AgentOutput represents what every agent returns.
type AgentOutput struct {
	// Response generated by this agent
	Reply string

	// Updated context after this agent
	UpdatedContext domain.ConversationContext
}

// Agent is the common interface implemented by all agents.
type Agent interface {
	Name() string
	Run(ctx context.Context, in AgentInput) (AgentOutput, error)
}
